import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header/Header";
import Banner from "../components/Banner";
import PopularCategories from "../components/PopularCategories";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>
        <Banner />
        <PopularCategories />
      </main>
    </div>
  );
}
